name: Deploy to Domeneshop
on:
  push:
    branches:
      - main

# Dette fjerner advarselen og tvinger handlingene over på ny versjon
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kode
      uses: actions/checkout@v4

    - name: Sett opp Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24' # Oppdatert til versjon 24 her også

    - name: Installer avhengigheter
      run: npm install

    - name: Bygg Tailwind CSS
      run: npm run build

    - name: Synkroniser filer via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/ 
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          package.json
          package-lock.json
          tailwind.config.js
          css/input.css
          **/*.jsx